# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sending-email:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: failure()
    steps:
      - run: |
          echo "<h1> Тесты прошли с ошибкой!  </h1> <div> <h2><a href="https://golosin.github.io/python_test/">Ссылка на отчет</a></h2></div>" > temp.html
      - name: Send email, test report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_LOGIN }}
          password: ${{ secrets.GMAIL_PASS }}
          subject: Report Email
#          body: https://golosin.github.io/python_test/
          html_body: file://temp.html
          to: aaaagd6rbdesiqh4kt3d5ovsgm@mp30.slack.com
          from: ${{ secrets.GMAIL_LOGIN }}
          secure: true
          ignore_cert: true
          convert_markdown: true

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pipenv
        pipenv install
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@v1
#      with:
      # Optional: do not specify to match Chrome's version
#        chromedriver-version: '101.0.4951.41'
    - run: |
        google-chrome --version
        export DISPLAY=:99
        chromedriver --whitelisted-ips="" --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

    - name: Test with pytest
      id: test
      run: |
        pytest --alluredir=./allure-results test_t4
#      env:
#       DISPLAY: :99

    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: ./allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history

